Repository astarte-platform/astarte_vmq_plugin, pull requests merged in 2020-05, with the labels that each got.

#19 Dockerfile: move to root and enhance build process
  .github/workflows/pr-container-build-workflow.yaml
  CHANGELOG.md
  Dockerfile
Labels: enhancement

#20 Update VerneMQ and deps
  Dockerfile
  docker/bin/vernemq.sh
  lib/astarte_vmq_plugin/rpc/handler.ex
  mix.exs
  mix.lock
  test/support/mock_verne.ex
Labels: chore

#21 Write SSL configuration to vernemq.conf only if SSL is enabled
  docker/bin/vernemq.sh
  docker/files/vernemq.conf
Labels: bug

#18 Support SSL for RabbitMQ connections
  lib/astarte_vmq_plugin/config.ex
  priv/astarte_vmq_plugin.schema
Labels: enhancement

#23 Prepare 0.11.1 release
  CHANGELOG.md
  mix.exs
  mix.lock
Labels: chore

#24 Default max certificate chain length to 10
  CHANGELOG.md
  lib/astarte_vmq_plugin/config.ex
Labels: user experience

#25 Reply to publish requests with local and remote matches
  CHANGELOG.md
  Dockerfile
  lib/astarte_vmq_plugin/rpc/handler.ex
  mix.lock
  test/astarte_vmq_plugin_rpc_test.exs
Labels: enhancement, user experience
