Repository astarte-platform/astarte_vmq_plugin, pull requests merged in 2020-04, with the labels that each got.

#14 Prepare 0.11.0
  mix.exs
  mix.lock
Labels: chore

#15 Prepare v0.11.0 release
  CHANGELOG.md
Labels: chore

#16 Send periodic heartbeat for each connected device
  CHANGELOG.md
  lib/astarte_vmq_plugin.ex
  lib/astarte_vmq_plugin/config.ex
  priv/astarte_vmq_plugin.schema
Labels: enhancement, user experience

#17 Enhance heartbeat configuration and add tests
  lib/astarte_vmq_plugin.ex
  lib/astarte_vmq_plugin/config.ex
  priv/astarte_vmq_plugin.schema
  test/astarte_vmq_plugin_test.exs
Labels: enhancement, testing
